### ISSUE TITLE
Build macros not located in "", use --with-opm-common= to specify!

### ISSUE THREAD

**Issue by rksin8** [OPM/opm-grid#276]
Hello, I am trying to install opm-parser in Ubuntu 16.04. While configuring, I am getting an error `"Build macros not located in "", use --with-opm-common= to specify!"`. Can anyone tell me how to solve this problem?

**Comment by joakim-hove** [comment]
Hello;

you are mentioning opm-parser - but your post is in the opm-grid repository; and I also think it should be possible to install opm-grid without opm-parser. But - assuming your problem is indeed with opm-parser:

The bulk of the cmake machinery in the opm build system is the opm-common module, that means that when building opm you must *always* start with the opm-common module. The opm build system has a notion of *sibling builds* - where the build system can locate dependencies if the modules are located side by side in the filesystem, i.e. you should clone opm-common and opm-parser like this:
```txt
opm-common/
opm-parser/
...
```
If you have more problems building opm-parser I suggest you create an issue in that repository.

**Comment by blattms** [comment]
Please try passing the directory of opm-common to cmake (the message
is still from the time of  autotools), by adding
"-DOPM_COMMON_ROOT=/full/path/to/opm-common" as an option to the CMake
command.

**Comment by blattms** [comment]
Sorry, wrong answer. you seem to use `configure` for whatever reason. In this case please use the configure option `--with-opm-common=/full/path/to/opm-common` like requested.

BTW: What build instructions are you following? You are aware that there are packages for [Ubuntu?](http://opm-project.org/?page_id=245)

**Comment by blattms** [comment]
I tried to replicate this with the current release. But it works for me without setting the location of opm-core, as I have all modules lying side by side in the same directory and am building a module
in directory <module>/build.
```
dir
|-- opm-common
|-- opm-parser
|-- opm-grid
```

You will need to give us more Information. What versions are you using, how the directory layout, how are you building...

**Comment by rksin8** [comment]
I apologize for replying this late. OPM modules alone work fine but I faced issues when it is installed as dune module. Anyway, Now I am using OPM modules separately (not as dune module).  Thank you for your help!

**Comment by blattms** [comment]
FYI we have made some fixes to use OPM modules from DUNE modules, see discussion in #327. Maybe that helps.

Closing this issue for now.
